version: '3.7'
services:
  ark:
    image: turzam/ark
    container_name: ark-crystal-isles
    ports:
      - "7779:7779"
      - "7779:7779/udp"
      - "7780:7780"
      - "7780:7780/udp"
      - "27016:27016"
      - "27016:27016/udp"
      - "32331:32330"
    restart: always
    volumes:
      - /mnt/ark-crystal-isles:/ark
      - /mnt/ark-crystal-isles-root:/root
    environment:
      SERVERMAP: CrystalIsles
      SESSIONNAME: kuroneko_park
      ADMINPASSWORD: 1qazse4rfvgy7
      SERVERPASSWORD: taroisgod
      SERVERPORT: 27016
      STEAMPORT: 7780
      TZ: Asia/Tokyo
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rwm
    entrypoint: >
      sh -c "
        sh /root/container-init.sh && /home/steam/user.sh
      "

