version: '3.7'
services:
  ark:
    image: turzam/ark
    container_name: ark_server
    ports:
      - "7777:7777"
      - "7777:7777/udp"
      - "7778:7778"
      - "7778:7778/udp"
      - "27015:27015"
      - "27015:27015/udp"
      - "32330:32330"
    restart: always
    volumes:
      - ark:/ark
    environment:
      SESSIONNAME: kuroneko_park
      ADMINPASSWORD: qawsedrftgyhujikolp
      SERVERPASSWORD: taroisgod
      TZ: Asia/Tokyo

volumes:
  ark:
